### ISSUE TITLE
aw-qt.toml autostart vs. (Gnome Tweaks) Autostart

### ISSUE THREAD

**Issue by luisgerhorst** [2e3s/awatcher#14]
Works great for me, thanks a lot! Only one little question regarding the suggested autostart method.

Reading https://github.com/2e3s/awatcher/blob/ba52553ddf2f8189f28d85591d0425cb8c7828f8/README.md?plain=1#L20 seems to conflict with https://github.com/2e3s/awatcher/blob/ba52553ddf2f8189f28d85591d0425cb8c7828f8/README.md?plain=1#L126

Does this mean the suggested method is to not add it to `autostart` in `aw-qt/aw-qt.toml` but instead to use (Gnome Tweaks) Autostart? Or does the latter only refer to the bundle with built-in ActivityWatch?

**Comment by 2e3s** [comment]
Thank you, this is indeed confusing, adjusted readmi in https://github.com/2e3s/awatcher/commit/5a8a0bfd4865fbd624e22aa2f04db7d8aa4a960c

**Comment by luisgerhorst** [comment]
I added a nit in https://github.com/2e3s/awatcher/pull/15 and added a mention of the name in Timeline (at least I would have expected the name there to be `aw-awatcher-*`.
