### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by OsoRojo** [2e3s/awatcher#17]
It looks like AW has release 12.2 with quite a few fixes and a timeline view in the web ui.  Any chance of updating, particularly the bundle?

**Comment by 2e3s** [comment]
Hello, I did bind to [v0.12.2](https://github.com/ActivityWatch/activitywatch/releases/tag/v0.12.2) (Mar 22), e.g. [webui](https://github.com/ActivityWatch/aw-webui/commit/839366e66f859faadd7f9128de3bea14b25ce4ae) (Mar 25). What are the fixes and timeline view that v0.12.2 does have and the bundle doesn't?

I see that there are pre-releases for v0.12.3, which are sometimes buggy, so I was waiting before integrating it. I probably could create a special branch and which binds to pre-released betas of ActivityWatch over v0.12.3, but not sure it would be in demand.

**Comment by OsoRojo** [comment]
Sorry, forgot about this!  I think I just noticed it flagging in the UI that 12.2 is available and asks to upgrade.  There aren't honestly any features I'm aware of that I'm desiring.  LOL.

**Comment by 2e3s** [comment]
Yes, I understand that message can be confusing. Not sure why it shows, probably it could be fixed. It's very low priority to get rid though, IMO for me.
