### ISSUE TITLE
Firefox unknown category

### ISSUE THREAD

**Issue by 7h3kk1d** [2e3s/awatcher#26]
Thanks so much for the work on this and having it work under wayland.

I'm having some issues with Firefox being completely uncategorized since the title is just being reported as firefox. I have the firefox extension which is reporting tab titles in the browser section but as far as I know browser entries aren't categorized like application titles. Let me know if I'm doing something wrong or if there's a contribution I can provide.

![Application tracking showing firefox as unknown](https://github.com/user-attachments/assets/8ff82e1e-42e6-45f4-9b6e-422a8c6e3241)
![Browser tracking uncategorized](https://github.com/user-attachments/assets/46bf2eb5-d023-4cef-bdf9-95b3256c1db0)

**Comment by 2e3s** [comment]
Hello!
> with Firefox being completely uncategorized since the title is just being reported as firefox

On screenshots I see that all "Top Window Titles" are categorized and reported, e.g. "ActivityWatch - Mozilla Firefox". "firefox" is not categorized in "Top Applications" which is a list of executable binaries. So this looks correct, at least on screenshots?

**Comment by 7h3kk1d** [comment]
I think I just misunderstood how the Top Applications worked. Thanks for the response.
